backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'


publish_mode: editorial_workflow

media_folder: "source/images/uploads"
public_folder: "/images/uploads"

logo_url: https://cdn.jsdelivr.net/gh/hoochanlon/picx-images-hosting@master/special/avatar.svg
site_url: https://blogger.hoochanlon.space
display_url: https://blogger.hoochanlon.space

locale: "zh_Hans"

collections:
  - name: "posts"
    label: "文章" # 在用户界面中使用，必须要配置的，不然会报错
    folder: "source/_posts/{{date.year}}/{{date.month}}/{{date.day}}-{{slug}}.md"  # 文件路径格式
    create: true
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm:ss", required: false}
      - {label: "更新日期", name: "updated", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm:ss", required: false}
      - {label: "标签", name: "tags", widget: "list", required: false}
      - {label: "分类", name: "categories", widget: "list", required: false}
      - {label: "关键词", name: "keywords", widget: "list", required: false}
      - {label: "摘要", name: "description", widget: "string", required: false}
      - {label: "评论", name: "comments", widget: "boolean", default: true, required: false}
      - {label: "密码", name: "password", widget: "string", required: false}
      - {label: "封面图片", name: "cover", widget: "image", required: false} # 封面图片字段
      - {label: "是否过期", name: "noticeOutdate", widget: "boolean", default: false, required: false} # 过期提醒字段
      - {label: "内容", name: "body", widget: "markdown", required: false}
